export const API_URL_PATH = '/api';
export const CLIENT_DIST_DIR = '/dist';
export const ENV_DEV = 'development';
export const HTTP_DEFAULT_PREFIX = '/';
export const HTTP_INTERNAL_ERROR = 500;
export const HTTP_NOT_FOUND = 404;
export const PORT = 3000;
export const PUBLIC_DIR = '/public';
export const ASSETS_MAX_AGE_MS = 365 * 24 * 60 * 60 * 1000;
