export * from './autoEditChange';
export * from './createAutoCloseMap';
export * from './exportAsImage';
export * from './fileSaver';
export { formatCode } from './formatCode';
export * from './getCursorPosition';
export * from './getDiff';
export * from './getLine';
export * from './getLineBeforeCursor';
export * from './getLineIndent';
export * from './highlightCode';
export * from './isCodePortionEnd';
export * from './isIntoAutoCloseGroup';
export * from './openFile';
export * from './spliceString';
